# Generated by Django 5.2.7 on 2025-10-13 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Categoria')),
            ],
            options={
                'verbose_name': 'Categoria do Item',
                'verbose_name_plural': 'Categorias dos Itens',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome da Marca')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='StatusItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Status')),
            ],
            options={
                'verbose_name': 'Status do Item',
                'verbose_name_plural': 'Status dos Itens',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome do Tipo')),
            ],
            options={
                'verbose_name': 'Tipo de Item',
                'verbose_name_plural': 'Tipos de Itens',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_item', models.CharField(max_length=200, verbose_name='Nome do Item')),
                ('modelo', models.CharField(blank=True, max_length=100)),
                ('etiqueta_servico_dell', models.CharField(blank=True, max_length=50, verbose_name='Etiqueta de Serviço Dell (S/N)')),
                ('hostname', models.CharField(blank=True, max_length=100, verbose_name='Hostname (Nome na Rede)')),
                ('data_compra', models.DateField(blank=True, null=True, verbose_name='Data da Compra')),
                ('loja_compra', models.CharField(blank=True, max_length=100, verbose_name='Loja da Compra')),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor Pago (R$)')),
                ('pago_por', models.CharField(blank=True, choices=[('EMPRESA', 'Empresa'), ('SOCIO', 'Sócio'), ('REEMBOLSO', 'Reembolso'), ('PESSOAL', 'Pessoal')], max_length=10, verbose_name='Pago por')),
                ('telefone_usuario', models.CharField(blank=True, help_text='Telefone de contato direto do responsável.', max_length=20, verbose_name='Telefone do Usuário')),
                ('anydesk', models.CharField(blank=True, max_length=50, verbose_name='AnyDesk')),
                ('categoria_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipamentos.categoriaitem', verbose_name='Categoria do Item')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável pelo Item')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipamentos.marca')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipamentos.statusitem', verbose_name='Status do Item')),
                ('tipo_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipamentos.tipoitem', verbose_name='Tipo do Item')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
                'ordering': ['nome_item'],
            },
        ),
    ]
