# Generated by Django 5.2.7 on 2025-12-01 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='espaco_disco',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Espaço em Disco'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='memoria_ram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Memória RAM'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='processador',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Processador (CPU)'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='sistema_operacional',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='SO Instalado'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='softwares_instalados',
            field=models.TextField(blank=True, help_text='Lista gerada automaticamente', null=True, verbose_name='Softwares Instalados'),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='ultima_auditoria',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Última Leitura'),
        ),
    ]
