# Generated by Django 5.2.8 on 2025-11-13 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casos', '0005_caso_valor_apurado'),
        ('clientes', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Modelo')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('descricoes_campos', models.JSONField(blank=True, default=dict, help_text='Dicionário com descrições de como encontrar cada campo', verbose_name='Descrições dos Campos')),
                ('instrucoes_gerais', models.TextField(blank=True, default='Você é um assistente especializado em análise de documentos jurídicos.\nSeja preciso e atencioso. Se não encontrar uma informação, retorne "Não encontrado".', verbose_name='Instruções Gerais')),
                ('gerar_resumo', models.BooleanField(default=True, verbose_name='Gerar Resumo do Caso')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos_analise', to='clientes.cliente', verbose_name='Cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelos_analise_criados', to=settings.AUTH_USER_MODEL)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos_analise', to='produtos.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Modelo de Análise',
                'verbose_name_plural': 'Modelos de Análise',
                'ordering': ['cliente', 'produto', 'nome'],
                'unique_together': {('cliente', 'produto', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='ResultadoAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivos_analisados', models.JSONField(default=list, verbose_name='Arquivos Analisados')),
                ('dados_extraidos', models.JSONField(default=dict, verbose_name='Dados Extraídos')),
                ('resumo_caso', models.TextField(blank=True, null=True, verbose_name='Resumo do Caso')),
                ('status', models.CharField(choices=[('PROCESSANDO', 'Processando'), ('CONCLUIDO', 'Concluído'), ('ERRO', 'Erro')], default='PROCESSANDO', max_length=20, verbose_name='Status')),
                ('mensagem_erro', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
                ('aplicado_ao_caso', models.BooleanField(default=False, verbose_name='Aplicado ao Caso')),
                ('data_aplicacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aplicação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('tempo_processamento', models.DurationField(blank=True, null=True, verbose_name='Tempo de Processamento')),
                ('aplicado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises_aplicadas', to=settings.AUTH_USER_MODEL, verbose_name='Aplicado Por')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analises', to='casos.caso', verbose_name='Caso')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analises_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
                ('modelo_usado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados', to='analyser.modeloanalise', verbose_name='Modelo Usado')),
            ],
            options={
                'verbose_name': 'Resultado de Análise',
                'verbose_name_plural': 'Resultados de Análises',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='LogAnalise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('nivel', models.CharField(choices=[('INFO', 'Informação'), ('WARNING', 'Aviso'), ('ERROR', 'Erro'), ('SUCCESS', 'Sucesso')], default='INFO', max_length=20)),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('detalhes', models.JSONField(blank=True, null=True, verbose_name='Detalhes')),
                ('resultado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='analyser.resultadoanalise', verbose_name='Resultado')),
            ],
            options={
                'verbose_name': 'Log de Análise',
                'verbose_name_plural': 'Logs de Análises',
                'ordering': ['timestamp'],
            },
        ),
    ]
