# Generated by Django 5.2.7 on 2025-10-13 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_campo', models.CharField(max_length=100, unique=True, verbose_name='Nome do Campo')),
                ('tipo_campo', models.CharField(choices=[('TEXTO', 'Texto Curto (String)'), ('NUMERO_INT', 'Número Inteiro'), ('NUMERO_DEC', 'Número Decimal'), ('LISTA_UNICA', 'Lista de Escolha Única'), ('LISTA_MULTIPLA', 'Lista de Escolha Múltipla'), ('DATA', 'Data')], max_length=20, verbose_name='Tipo do Campo')),
                ('opcoes_lista', models.TextField(blank=True, help_text='Ex: Opção A, Opção B, Opção C', verbose_name='Opções (para campos de lista, separadas por vírgula)')),
            ],
        ),
        migrations.CreateModel(
            name='ValorCampoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obrigatorio', models.BooleanField(default=False)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campos_custom.campopersonalizado', verbose_name='Campo da Biblioteca')),
            ],
            options={
                'ordering': ['ordem'],
            },
        ),
    ]
