# Generated by Django 5.2.7 on 2025-10-14 20:47

import campos_custom.models
import django.db.models.deletion
from django.db import migrations, models
# IMPORTAÇÃO CORRIGIDA: Importa a função de validação (que agora está fora da classe)
from campos_custom.models import validate_variable_name 


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_campo', models.CharField(max_length=100, verbose_name='Nome Visível (Rótulo)')),
                # CORREÇÃO NA LINHA ABAIXO: Usa a função importada 'validate_variable_name'
                ('nome_variavel', models.CharField(
                    help_text='Ex: NumeroAviso, ValorCausa, DataSentenca. Sem espaços ou caracteres especiais.', 
                    max_length=50, 
                    unique=True, 
                    validators=[validate_variable_name], # <<< AQUI ESTÁ A CORREÇÃO
                    verbose_name='Nome da Variável (para relatórios)'
                )),
                ('tipo_campo', models.CharField(choices=[('TEXTO', 'Texto Curto (String)'), ('NUMERO_INT', 'Número Inteiro'), ('NUMERO_DEC', 'Número Decimal'), ('MOEDA', 'Moeda (R$)'), ('LISTA_USUARIOS', 'Lista de Usuários'), ('LISTA_UNICA', 'Lista de Opções (Escolha Única)'), ('LISTA_MULTIPLA', 'Lista de Opções (Escolha Múltipla)'), ('DATA', 'Data')], max_length=20, verbose_name='Tipo do Campo')),
                ('opcoes_lista', models.TextField(blank=True, help_text='Separadas por vírgula. Ex: Opção A, Opção B', verbose_name='Opções (para Lista de Opções)')),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracaoCampoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obrigatorio', models.BooleanField(default=False)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campos_custom.campopersonalizado', verbose_name='Campo da Biblioteca')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Configuração de Campo Personalizado',
                'verbose_name_plural': 'Configurações de Campos Personalizados',
                'ordering': ['cliente', 'produto', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='EstruturaCampoOrdenado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campos_custom.campopersonalizado')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='EstruturaDeCampos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campos', models.ManyToManyField(blank=True, through='campos_custom.EstruturaCampoOrdenado', to='campos_custom.campopersonalizado', verbose_name='Campos Personalizados')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Estrutura de Campos',
                'verbose_name_plural': 'Estruturas de Campos',
            },
        ),
        migrations.AddField(
            model_name='estruturacampoordenado',
            name='estrutura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campos_custom.estruturadecampos'),
        ),
        migrations.CreateModel(
            name='ValorCampoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField(blank=True, null=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campos_custom.campopersonalizado')),
            ],
        ),
    ]