# Generated by Django 5.2.7 on 2025-10-10 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casos', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_campo', models.CharField(max_length=100, verbose_name='Nome do Campo')),
                ('tipo_campo', models.CharField(choices=[('TEXTO', 'Texto Curto (String)'), ('NUMERO_INT', 'Número Inteiro'), ('NUMERO_DEC', 'Número Decimal'), ('LISTA_UNICA', 'Lista de Escolha Única'), ('LISTA_MULTIPLA', 'Lista de Escolha Múltipla'), ('DATA', 'Data')], max_length=20, verbose_name='Tipo do Campo')),
                ('opcoes_lista', models.TextField(blank=True, help_text='Ex: Opção A, Opção B, Opção C', verbose_name='Opções (para campos de lista, separadas por vírgula)')),
                ('obrigatorio', models.BooleanField(default=False)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Define a ordem de exibição no formulário.')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos_personalizados', to='produtos.produto')),
            ],
            options={
                'ordering': ['produto', 'ordem'],
                'unique_together': {('produto', 'nome_campo')},
            },
        ),
        migrations.CreateModel(
            name='ValorCampoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField(blank=True, null=True)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campos_custom.campopersonalizado')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_personalizados', to='casos.caso')),
            ],
        ),
    ]
