# Generated by Django 5.2.7 on 2025-10-12 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos_custom', '0001_initial'),
        ('produtos', '0002_produto_padrao_titulo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campopersonalizado',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='campopersonalizado',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='campopersonalizado',
            name='nome_campo',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome do Campo'),
        ),
        migrations.RemoveField(
            model_name='campopersonalizado',
            name='obrigatorio',
        ),
        migrations.RemoveField(
            model_name='campopersonalizado',
            name='ordem',
        ),
        migrations.RemoveField(
            model_name='campopersonalizado',
            name='produto',
        ),
        migrations.CreateModel(
            name='ProdutoCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obrigatorio', models.BooleanField(default=False)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campos_custom.campopersonalizado', verbose_name='Campo da Biblioteca')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
            options={
                'ordering': ['ordem'],
                'unique_together': {('produto', 'campo')},
            },
        ),
    ]
