# Generated by Django 5.2.7 on 2025-10-13 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campos_custom', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtocampo',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto'),
        ),
        migrations.AddField(
            model_name='valorcampopersonalizado',
            name='campo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campos_custom.campopersonalizado'),
        ),
    ]
