# Generated by Django 5.2.7 on 2025-10-27 20:22

import campos_custom.models
import django.db.models.deletion
from django.db import migrations, models
from campos_custom.models import validate_variable_name # <<< ESTA LINHA CORRIGE O IMPORTERROR

class Migration(migrations.Migration):

    dependencies = [
        ('campos_custom', '0002_initial'),
        ('casos', '0003_alter_caso_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='configuracaocampopersonalizado',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='configuracaocampopersonalizado',
            name='campo',
        ),
        migrations.RemoveField(
            model_name='configuracaocampopersonalizado',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='configuracaocampopersonalizado',
            name='produto',
        ),
        migrations.AlterField(
            model_name='campopersonalizado',
            name='nome_variavel',
            # CORRIGIDO AQUI: Removemos 'campos_custom.models.CampoPersonalizado.'
            field=models.CharField(help_text='Ex: NumeroAviso, ValorCausa. Sem espaços ou caracteres especiais.', max_length=50, unique=True, validators=[validate_variable_name], verbose_name='Nome da Variável (para relatórios)'), 
        ),
        migrations.AlterField(
            model_name='estruturadecampos',
            name='campos',
            field=models.ManyToManyField(blank=True, through='campos_custom.EstruturaCampoOrdenado', to='campos_custom.campopersonalizado', verbose_name='Campos Personalizados (Não Repetíveis)'),
        ),
        migrations.AlterField(
            model_name='valorcampopersonalizado',
            name='caso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valores_personalizados', to='casos.caso'),
        ),
        migrations.AlterUniqueTogether(
            name='valorcampopersonalizado',
            unique_together={('caso', 'campo')},
        ),
        migrations.CreateModel(
            name='GrupoCampoOrdenado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campos_custom.campopersonalizado')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GrupoCampos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_grupo', models.CharField(max_length=100, verbose_name='Nome do Grupo')),
                ('campos', models.ManyToManyField(blank=True, through='campos_custom.GrupoCampoOrdenado', to='campos_custom.campopersonalizado', verbose_name='Campos do Grupo')),
                ('estrutura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_repetiveis', to='campos_custom.estruturadecampos')),
            ],
            options={
                'verbose_name': 'Grupo de Campos Repetível',
                'verbose_name_plural': 'Grupos de Campos Repetíveis',
            },
        ),
        migrations.AddField(
            model_name='grupocampoordenado',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campos_custom.grupocampos'),
        ),
        migrations.CreateModel(
            name='InstanciaGrupoValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem_instancia', models.PositiveIntegerField(db_index=True, default=0)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_de_valores', to='casos.caso')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instancias', to='campos_custom.grupocampos')),
            ],
            options={
                'ordering': ['ordem_instancia'],
            },
        ),
        migrations.AddField(
            model_name='valorcampopersonalizado',
            name='instancia_grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='campos_custom.instanciagrupovalor'),
        ),
        migrations.AddConstraint(
            model_name='valorcampopersonalizado',
            constraint=models.UniqueConstraint(fields=('instancia_grupo', 'campo'), name='unique_valor_em_grupo'),
        ),
        migrations.DeleteModel(
            name='ConfiguracaoCampoPersonalizado',
        ),
        migrations.AlterUniqueTogether(
            name='grupocampoordenado',
            unique_together={('grupo', 'campo')},
        ),
    ]