# Generated by Django 5.2.7 on 2025-10-13 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campos_custom', '0002_initial'),
        ('casos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorcampopersonalizado',
            name='caso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_personalizados', to='casos.caso'),
        ),
        migrations.AlterUniqueTogether(
            name='produtocampo',
            unique_together={('produto', 'campo')},
        ),
    ]
