# Generated by Django 5.2.7 on 2025-10-13 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos_custom', '0003_initial'),
        ('clientes', '0001_initial'),
        ('produtos', '0002_remove_produto_campos_personalizados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campopersonalizado',
            name='nome_campo',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome do Campo na Biblioteca'),
        ),
        migrations.CreateModel(
            name='ConfiguracaoCampoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obrigatorio', models.BooleanField(default=False)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campos_custom.campopersonalizado', verbose_name='Campo da Biblioteca')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Configuração de Campo Personalizado',
                'verbose_name_plural': 'Configurações de Campos Personalizados',
                'ordering': ['cliente', 'produto', 'ordem'],
                'unique_together': {('cliente', 'produto', 'campo')},
            },
        ),
        migrations.DeleteModel(
            name='ProdutoCampo',
        ),
    ]
