# Generated by Django 5.2.7 on 2025-10-28 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos_custom', '0003_alter_configuracaocampopersonalizado_unique_together_and_more'),
        ('clientes', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campopersonalizado',
            name='opcoes_lista',
        ),
        migrations.AlterField(
            model_name='estruturacampoordenado',
            name='estrutura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenamentos_simples', to='campos_custom.estruturadecampos'),
        ),
        migrations.AlterField(
            model_name='grupocampoordenado',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenamentos_grupo', to='campos_custom.grupocampos'),
        ),
        migrations.CreateModel(
            name='OpcoesListaPersonalizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcoes_lista', models.TextField(help_text='Separadas por vírgula. Ex: Opção A, Opção B', verbose_name='Opções de Lista')),
                ('campo', models.ForeignKey(limit_choices_to={'tipo_campo__in': ['LISTA_UNICA', 'LISTA_MULTIPLA']}, on_delete=django.db.models.deletion.CASCADE, to='campos_custom.campopersonalizado', verbose_name='Campo de Lista')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Opção de Lista Customizada',
                'verbose_name_plural': 'Opções de Lista Customizadas',
                'unique_together': {('campo', 'cliente', 'produto')},
            },
        ),
    ]
