# Generated by Django 5.2.7 on 2025-10-13 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos_custom', '0004_alter_campopersonalizado_nome_campo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campopersonalizado',
            name='tipo_campo',
            field=models.CharField(choices=[('TEXTO', 'Texto Curto (String)'), ('NUMERO_INT', 'Número Inteiro'), ('NUMERO_DEC', 'Número Decimal'), ('MOEDA', 'Moeda (R$)'), ('LISTA_USUARIOS', 'Lista de Usuários'), ('LISTA_UNICA', 'Lista de Opções (Escolha Única)'), ('LISTA_MULTIPLA', 'Lista de Opções (Escolha Múltipla)'), ('DATA', 'Data')], max_length=20, verbose_name='Tipo do Campo'),
        ),
    ]
