# Generated by Django 5.2.7 on 2025-10-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos_custom', '0004_remove_campopersonalizado_opcoes_lista_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estruturacampoordenado',
            name='obrigatorio',
            field=models.BooleanField(default=False, verbose_name='Obrigatório'),
        ),
    ]
