# Generated by Django 5.2.8 on 2025-11-10 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos_custom', '0005_estruturacampoordenado_obrigatorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campopersonalizado',
            name='tipo_campo',
            field=models.CharField(choices=[('TEXTO', 'Texto Curto (String)'), ('NUMERO_INT', 'Número Inteiro'), ('NUMERO_DEC', 'Número Decimal'), ('MOEDA', 'Moeda (R$)'), ('LISTA_USUARIOS', 'Lista de Usuários'), ('LISTA_UNICA', 'Lista de Opções (Escolha Única)'), ('LISTA_MULTIPLA', 'Lista de Opções (Escolha Múltipla)'), ('DATA', 'Data'), ('BOOLEANO', 'Sim/Não (Checkbox)')], max_length=20, verbose_name='Tipo do Campo'),
        ),
    ]
