# Generated by Codex on 2026-01-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos_custom', '0006_alter_campopersonalizado_tipo_campo'),
    ]

    operations = [
        migrations.AddField(
            model_name='campopersonalizado',
            name='mascara',
            field=models.CharField(
                blank=True,
                null=True,
                max_length=100,
                verbose_name='MÇ­scara de Entrada',
                help_text=("Ex: 000.000.000-00, (00) 0000-0000, SSS-0A00. "
                           "Use '0' para nÇ§meros e 'S' para letras.")
            ),
        ),
    ]
