# Generated by Django 5.2.7 on 2025-10-13 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campos_custom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('padrao_titulo', models.CharField(blank=True, help_text='Crie um padrão para o título. Use {NomeDoCampo} para inserir valores. Ex: Aviso {NumeroAviso} - Segurado {NomeSegurado}', max_length=255, verbose_name='Padrão do Título do Caso')),
                ('campos_personalizados', models.ManyToManyField(blank=True, related_name='produtos', through='campos_custom.ProdutoCampo', to='campos_custom.campopersonalizado', verbose_name='Campos Personalizados')),
            ],
        ),
    ]
