# Generated by Django 5.2.7 on 2025-10-13 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='campos_personalizados',
        ),
    ]
