# Generated by Django 5.2.7 on 2025-10-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='padrao_titulo',
            field=models.CharField(blank=True, help_text='Crie um padrão para o título. Use {NomeDoCampo} para inserir valores. Ex: Aviso {NumeroAviso} - Segurado {NomeSegurado}', max_length=255, verbose_name='Padrão do Título do Caso'),
        ),
    ]
