# Generated by Django 5.2.7 on 2025-10-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campos_custom', '0002_alter_campopersonalizado_options_and_more'),
        ('produtos', '0002_produto_padrao_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='campos_personalizados',
            field=models.ManyToManyField(blank=True, related_name='produtos', through='campos_custom.ProdutoCampo', to='campos_custom.campopersonalizado', verbose_name='Campos Personalizados'),
        ),
    ]
