# Generated by Django 5.2.7 on 2025-10-13 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casos', '0001_initial'),
        ('clientes', '0001_initial'),
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.PositiveIntegerField(help_text="Define a sequência das fases. A fase com ordem '1' é a inicial.")),
                ('eh_fase_final', models.BooleanField(default=False, verbose_name='É Fase Final?')),
            ],
            options={
                'verbose_name': 'Fase',
                'verbose_name_plural': '2. Fases do Workflow',
                'ordering': ['workflow', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título da Ação')),
                ('tipo', models.CharField(choices=[('SIMPLES', 'Ação Simples (Apenas confirmação)'), ('DECISAO_SN', 'Decisão (Sim/Não)'), ('AGUARDAR_DIAS', 'Aguardar (Dispara nova ação após X dias)')], default='SIMPLES', max_length=20)),
                ('prazo_dias', models.PositiveIntegerField(default=0, help_text='0 para nenhum prazo. Contado a partir da criação da ação.', verbose_name='Prazo (em dias)')),
                ('dias_aguardar', models.PositiveIntegerField(default=0, help_text="Use apenas para o tipo 'Aguardar'.", verbose_name='Dias para Aguardar')),
                ('mudar_status_caso_para', models.CharField(blank=True, choices=[('', 'Não alterar'), ('ATIVO', 'Ativo'), ('ENCERRADO', 'Encerrado'), ('AGUARDANDO_DOC', 'Aguardando Documentação'), ('EM_NEGOCIACAO', 'Em Negociação')], max_length=20, verbose_name='Ao concluir, mudar Status do Caso para')),
                ('responsavel_padrao', models.ForeignKey(blank=True, help_text='Se definido, esta ação será atribuída a este usuário por padrão.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável Padrão')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='workflow.fase')),
            ],
            options={
                'verbose_name': 'Ação',
                'verbose_name_plural': '3. Ações da Fase',
            },
        ),
        migrations.CreateModel(
            name='HistoricoFase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_fases', to='casos.caso')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.fase')),
            ],
        ),
        migrations.CreateModel(
            name='InstanciaAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDA', 'Concluída')], default='PENDENTE', max_length=20)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('resposta', models.CharField(blank=True, help_text='Ex: SIM, NAO', max_length=10)),
                ('data_prazo', models.DateField(blank=True, null=True, verbose_name='Prazo de Conclusão')),
                ('comentario', models.TextField(blank=True, verbose_name='Comentário de Conclusão')),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.acao')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes_pendentes', to='casos.caso')),
                ('concluida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela Ação')),
            ],
        ),
        migrations.CreateModel(
            name='Transicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicao', models.CharField(blank=True, choices=[('', 'Sempre (para Ação Simples)'), ('SIM', 'Se a resposta for SIM'), ('NAO', 'Se a resposta for NÃO')], max_length=10, verbose_name='Condição para transição')),
                ('acao', models.ForeignKey(help_text='A ação que dispara esta transição.', on_delete=django.db.models.deletion.CASCADE, to='workflow.acao')),
                ('fase_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transicoes_entrada', to='workflow.fase')),
                ('fase_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transicoes_saida', to='workflow.fase')),
            ],
            options={
                'verbose_name': 'Transição',
                'verbose_name_plural': '4. Transições entre Fases',
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Workflow de Sinistro RCG para Tokio', max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': '1. Workflows (Configuração)',
                'unique_together': {('cliente', 'produto')},
            },
        ),
        migrations.AddField(
            model_name='fase',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='workflow.workflow'),
        ),
        migrations.AlterUniqueTogether(
            name='fase',
            unique_together={('workflow', 'ordem')},
        ),
    ]
