# Generated by Django 5.2.7 on 2025-10-12 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casos', '0007_caso_sharepoint_folder_id'),
        ('clientes', '0001_initial'),
        ('produtos', '0003_produto_campos_personalizados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.PositiveIntegerField(help_text="Define a sequência das fases. A fase com ordem '1' é a inicial.")),
                ('eh_fase_final', models.BooleanField(default=False, verbose_name='É Fase Final?')),
            ],
            options={
                'verbose_name': 'Fase',
                'verbose_name_plural': '2. Fases do Workflow',
                'ordering': ['workflow', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255, verbose_name='Título da Ação')),
                ('tipo', models.CharField(choices=[('SIMPLES', 'Ação Simples (Apenas confirmação)'), ('DECISAO_SN', 'Decisão (Sim/Não)')], default='SIMPLES', max_length=20)),
                ('mudar_status_caso_para', models.CharField(blank=True, choices=[('', 'Não alterar'), ('Ativo', 'Ativo'), ('Encerrado', 'Encerrado'), ('Em monitoramento', 'Aguardando Documentação')], max_length=20, verbose_name='Mudar Status do Caso para')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='workflow.fase')),
            ],
            options={
                'verbose_name': 'Ação',
                'verbose_name_plural': '3. Ações da Fase',
            },
        ),
        migrations.CreateModel(
            name='HistoricoFase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_fases', to='casos.caso')),
                ('fase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.fase')),
            ],
        ),
        migrations.CreateModel(
            name='InstanciaAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDA', 'Concluída')], default='PENDENTE', max_length=20)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('resposta', models.CharField(blank=True, help_text='Ex: SIM, NAO', max_length=10)),
                ('acao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='workflow.acao')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes_pendentes', to='casos.caso')),
                ('concluida_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicao', models.CharField(blank=True, choices=[('', 'Sempre (para Ação Simples)'), ('SIM', 'Se a resposta for SIM'), ('NAO', 'Se a resposta for NÃO')], max_length=10, verbose_name='Condição para transição')),
                ('acao', models.ForeignKey(help_text='A ação que dispara esta transição.', on_delete=django.db.models.deletion.CASCADE, to='workflow.acao')),
                ('fase_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transicoes_entrada', to='workflow.fase')),
                ('fase_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transicoes_saida', to='workflow.fase')),
            ],
            options={
                'verbose_name': 'Transição',
                'verbose_name_plural': '4. Transições entre Fases',
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Workflow de Sinistro RCG para Tokio', max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Workflow',
                'verbose_name_plural': '1. Workflows (Configuração)',
                'unique_together': {('cliente', 'produto')},
            },
        ),
        migrations.AddField(
            model_name='fase',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='workflow.workflow'),
        ),
        migrations.AlterUniqueTogether(
            name='fase',
            unique_together={('workflow', 'ordem')},
        ),
    ]
