# Generated by Django 5.2.7 on 2025-10-12 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acao',
            name='dias_aguardar',
            field=models.PositiveIntegerField(default=0, help_text="Use apenas para o tipo 'Aguardar'.", verbose_name='Dias para Aguardar'),
        ),
        migrations.AddField(
            model_name='acao',
            name='prazo_dias',
            field=models.PositiveIntegerField(default=0, help_text='0 para nenhum prazo. Contado a partir da criação da ação.', verbose_name='Prazo (em dias)'),
        ),
        migrations.AddField(
            model_name='instanciaacao',
            name='comentario',
            field=models.TextField(blank=True, verbose_name='Comentário de Conclusão'),
        ),
        migrations.AddField(
            model_name='instanciaacao',
            name='data_prazo',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo de Conclusão'),
        ),
        migrations.AddField(
            model_name='instanciaacao',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='Responsável pela Ação'),
        ),
        migrations.AlterField(
            model_name='acao',
            name='mudar_status_caso_para',
            field=models.CharField(blank=True, choices=[('', 'Não alterar'), ('ATIVO', 'Ativo'), ('ENCERRADO', 'Encerrado'), ('AGUARDANDO_DOC', 'Aguardando Documentação'), ('EM_NEGOCIACAO', 'Em Negociação')], max_length=20, verbose_name='Ao concluir, mudar Status do Caso para'),
        ),
        migrations.AlterField(
            model_name='acao',
            name='tipo',
            field=models.CharField(choices=[('SIMPLES', 'Ação Simples (Apenas confirmação)'), ('DECISAO_SN', 'Decisão (Sim/Não)'), ('AGUARDAR_DIAS', 'Aguardar (Dispara nova ação após X dias)')], default='SIMPLES', max_length=20),
        ),
    ]
