# Generated by Django 5.2.7 on 2025-10-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acao',
            name='mudar_status_caso_para',
            field=models.CharField(blank=True, choices=[('', 'Não alterar'), ('ATIVO', 'Ativo'), ('ENCERRADO', 'Encerrado')], max_length=20, verbose_name='Ao concluir, mudar Status do Caso para'),
        ),
    ]
