# Generated by Django 5.2.7 on 2025-10-12 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_acao_dias_aguardar_acao_prazo_dias_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acao',
            name='responsavel_padrao',
            field=models.ForeignKey(blank=True, help_text='Se definido, esta ação será atribuída a este usuário por padrão.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável Padrão'),
        ),
    ]
