# Generated by Django 5.2.8 on 2025-11-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_alter_acao_mudar_status_caso_para'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPausa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ex: DOC_PENDENTE, VISTORIA, ANALISE_JURIDICA', max_length=50, unique=True, verbose_name='Código Único')),
                ('nome', models.CharField(help_text="Ex: 'Aguardando Documentação do Cliente'", max_length=200, verbose_name='Nome do Motivo')),
                ('descricao', models.TextField(blank=True, help_text='Quando usar este tipo de pausa?', verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para desativar este motivo', verbose_name='Ativo?')),
                ('cor', models.CharField(default='#ffc107', help_text='Ex: #ffc107 (amarelo), #dc3545 (vermelho)', max_length=7, verbose_name='Cor (Hexadecimal)')),
                ('icone', models.CharField(blank=True, default='fa-pause-circle', help_text='Ex: fa-clock, fa-file, fa-hourglass', max_length=50, verbose_name='Ícone Font Awesome')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Menor número aparece primeiro', verbose_name='Ordem de Exibição')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tipo de Pausa',
                'verbose_name_plural': 'Tipos de Pausa (Motivos)',
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
