# Generated by Django 5.2.8 on 2025-11-08 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0003_tipopausa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicofase',
            options={'ordering': ['-data_entrada'], 'verbose_name': 'Histórico de Fase', 'verbose_name_plural': '8. Histórico de Fases'},
        ),
        migrations.AlterModelOptions(
            name='instanciaacao',
            options={'ordering': ['-id'], 'verbose_name': 'Instância de Ação', 'verbose_name_plural': '9. Instâncias de Ações'},
        ),
        migrations.AlterModelOptions(
            name='tipopausa',
            options={'ordering': ['ordem', 'nome'], 'verbose_name': 'Tipo de Pausa', 'verbose_name_plural': '0. Tipos de Pausa'},
        ),
        migrations.AlterField(
            model_name='instanciaacao',
            name='concluida_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_concluidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
