# Generated by Django 5.2.8 on 2025-11-08 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_alter_historicofase_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='acao',
            name='nome_responsavel_terceiro',
            field=models.CharField(blank=True, help_text="Ex: 'Cliente', 'Perito João Silva', 'Seguradora XYZ'", max_length=200, verbose_name='Nome do Responsável Terceiro'),
        ),
        migrations.AddField(
            model_name='acao',
            name='pausar_prazo_enquanto_aguarda',
            field=models.BooleanField(default=False, help_text='✅ Útil para ações de terceiros (aguardando cliente, perito, etc)', verbose_name='Pausar Prazo Enquanto Aguarda esta Ação?'),
        ),
        migrations.AddField(
            model_name='acao',
            name='tipo_pausa_acao',
            field=models.ForeignKey(blank=True, help_text="Usado se 'Pausar Prazo' estiver marcado", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_com_pausa', to='workflow.tipopausa', verbose_name='Motivo da Pausa'),
        ),
        migrations.AddField(
            model_name='acao',
            name='tipo_responsavel',
            field=models.CharField(choices=[('INTERNO', 'Responsável Interno (Advogado/Regulador)'), ('TERCEIRO', 'Responsável Terceiro (Cliente/Fornecedor/Perito)')], default='INTERNO', help_text='Define quem é responsável por esta ação', max_length=20, verbose_name='Tipo de Responsável'),
        ),
        migrations.AddField(
            model_name='fase',
            name='cor_fase',
            field=models.CharField(default='#6c757d', help_text='Para Kanban. Ex: #28a745', max_length=7, verbose_name='Cor da Fase (Hex)'),
        ),
        migrations.AddField(
            model_name='fase',
            name='icone_fase',
            field=models.CharField(blank=True, default='fa-circle', max_length=50, verbose_name='Ícone Font Awesome'),
        ),
        migrations.AddField(
            model_name='fase',
            name='pausar_prazo_automaticamente',
            field=models.BooleanField(default=False, help_text='✅ Se marcado, o prazo para automaticamente quando o caso entra nesta fase', verbose_name='Pausar Prazo ao Entrar nesta Fase?'),
        ),
        migrations.AddField(
            model_name='fase',
            name='retomar_prazo_ao_sair',
            field=models.BooleanField(default=False, help_text='✅ Se marcado, o prazo volta a contar ao sair desta fase', verbose_name='Retomar Prazo ao Sair desta Fase?'),
        ),
        migrations.AddField(
            model_name='fase',
            name='tipo_pausa_padrao',
            field=models.ForeignKey(blank=True, help_text='Motivo que será usado quando pausar automaticamente', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.tipopausa', verbose_name='Motivo da Pausa (Padrão)'),
        ),
        migrations.AlterField(
            model_name='acao',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição da Tarefa'),
        ),
        migrations.AlterField(
            model_name='acao',
            name='dias_aguardar',
            field=models.PositiveIntegerField(default=0, verbose_name='Dias para Aguardar'),
        ),
        migrations.AlterField(
            model_name='acao',
            name='prazo_dias',
            field=models.PositiveIntegerField(default=0, help_text='0 = sem prazo', verbose_name='Prazo (em dias)'),
        ),
        migrations.AlterField(
            model_name='acao',
            name='responsavel_padrao',
            field=models.ForeignKey(blank=True, help_text='Usuário do sistema que será atribuído automaticamente', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável Padrão (se interno)'),
        ),
        migrations.AlterField(
            model_name='fase',
            name='ordem',
            field=models.PositiveIntegerField(help_text='Define a sequência das fases.'),
        ),
        migrations.AlterField(
            model_name='instanciaacao',
            name='comentario',
            field=models.TextField(blank=True, verbose_name='Comentário'),
        ),
        migrations.AlterField(
            model_name='instanciaacao',
            name='data_prazo',
            field=models.DateField(blank=True, null=True, verbose_name='Prazo'),
        ),
        migrations.AlterField(
            model_name='instanciaacao',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acoes_responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AlterField(
            model_name='instanciaacao',
            name='resposta',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='tipopausa',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='tipopausa',
            name='cor',
            field=models.CharField(default='#ffc107', max_length=7, verbose_name='Cor (Hexadecimal)'),
        ),
        migrations.AlterField(
            model_name='tipopausa',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='tipopausa',
            name='icone',
            field=models.CharField(blank=True, default='fa-pause-circle', max_length=50, verbose_name='Ícone Font Awesome'),
        ),
        migrations.AlterField(
            model_name='tipopausa',
            name='ordem',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição'),
        ),
        migrations.AlterField(
            model_name='transicao',
            name='acao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.acao'),
        ),
        migrations.AlterField(
            model_name='transicao',
            name='condicao',
            field=models.CharField(blank=True, choices=[('', 'Sempre'), ('SIM', 'Se SIM'), ('NAO', 'Se NÃO')], max_length=10, verbose_name='Condição'),
        ),
    ]
