# Generated by Django 5.2.8 on 2025-11-09 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_acao_nome_responsavel_terceiro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transicao',
            name='workflow',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transicoes', to='workflow.workflow'),
            preserve_default=False,
        ),
    ]
