# Generated by Django 5.2.7 on 2025-10-14 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_despesa', models.DateField(verbose_name='Data da Despesa')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Despesa')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição da Despesa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_despesa'],
            },
        ),
        migrations.CreateModel(
            name='FluxoInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('CRIACAO_CASO', 'Criação do Caso'), ('MUDANCA_FASE_WF', 'Mudança de Fase do Workflow'), ('ACAO_WF_CONCLUIDA', 'Ação de Workflow Concluída'), ('ANDAMENTO', 'Andamento Adicionado'), ('TIMESHEET', 'Timesheet Lançado'), ('ACORDO', 'Acordo Criado'), ('DESPESA', 'Despesa Lançada'), ('EMAIL', 'E-mail Enviado'), ('ANEXO', 'Anexo Adicionado')], max_length=20, verbose_name='Tipo do Evento')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_evento', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Evento do Fluxo Interno',
                'verbose_name_plural': 'Eventos do Fluxo Interno',
                'ordering': ['-data_evento'],
            },
        ),
        migrations.CreateModel(
            name='ModeloAndamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(verbose_name='Descrição Padrão')),
            ],
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.PositiveIntegerField(verbose_name='Nº da Parcela')),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Parcela')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('status', models.CharField(choices=[('EMITIDA', 'Emitida'), ('QUITADA', 'Quitada')], default='EMITIDA', max_length=10, verbose_name='Status do Pagamento')),
            ],
            options={
                'ordering': ['data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_execucao', models.DateField(verbose_name='Data da Execução')),
                ('tempo', models.DurationField(verbose_name='Tempo Gasto (HH:MM)')),
                ('descricao', models.TextField(verbose_name='Descrição do Trabalho Realizado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_execucao'],
            },
        ),
        migrations.CreateModel(
            name='Acordo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total do Acordo')),
                ('numero_parcelas', models.PositiveIntegerField(default=1, verbose_name='Número de Parcelas')),
                ('data_primeira_parcela', models.DateField(verbose_name='Data da 1ª Parcela')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('advogado_acordo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Advogado do Acordo')),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Andamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_andamento', models.DateField(verbose_name='Data do Andamento')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('autor', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'ordering': ['-data_andamento', '-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateField(verbose_name='Data de Entrada RCA')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('ENCERRADO', 'Encerrado'), ('AGUARDANDO_DOC', 'Aguardando Documentação'), ('EM_NEGOCIACAO', 'Em Negociação')], default='ATIVO', max_length=20)),
                ('sharepoint_folder_id', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('titulo', models.CharField(blank=True, max_length=255)),
                ('data_encerramento', models.DateField(blank=True, null=True, verbose_name='Data de Encerramento')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('advogado_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_responsaveis', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casos', to='clientes.cliente')),
            ],
        ),
    ]
