# Generated by Django 5.2.7 on 2025-10-10 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloAndamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(verbose_name='Descrição Padrão')),
            ],
        ),
        migrations.CreateModel(
            name='Andamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_andamento', models.DateField(verbose_name='Data do Andamento')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('autor', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='andamentos', to='casos.caso')),
            ],
            options={
                'ordering': ['-data_andamento', '-data_criacao'],
            },
        ),
    ]
