# Generated by Django 5.2.7 on 2025-10-14 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casos', '0001_initial'),
        ('produtos', '0001_initial'),
        ('workflow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='fase_atual_wf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.fase', verbose_name='Fase Atual do Workflow'),
        ),
        migrations.AddField(
            model_name='caso',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casos', to='produtos.produto'),
        ),
        migrations.AddField(
            model_name='andamento',
            name='caso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='andamentos', to='casos.caso'),
        ),
        migrations.AddField(
            model_name='acordo',
            name='caso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acordos', to='casos.caso'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='advogado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Advogado'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='caso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='casos.caso'),
        ),
        migrations.AddField(
            model_name='fluxointerno',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor da Ação'),
        ),
        migrations.AddField(
            model_name='fluxointerno',
            name='caso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fluxo_interno', to='casos.caso'),
        ),
        migrations.AddField(
            model_name='parcela',
            name='acordo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='casos.acordo'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='advogado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Advogado'),
        ),
        migrations.AddField(
            model_name='timesheet',
            name='caso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='casos.caso'),
        ),
        migrations.AlterUniqueTogether(
            name='parcela',
            unique_together={('acordo', 'numero_parcela')},
        ),
    ]
