# Generated by Django 5.2.7 on 2025-10-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('ENCERRADO', 'Encerrado')], default='ATIVO', max_length=20),
        ),
    ]
