# Generated by Django 5.2.7 on 2025-10-10 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0002_modeloandamento_andamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_execucao', models.DateField(verbose_name='Data da Execução')),
                ('tempo', models.DurationField(verbose_name='Tempo Gasto (HH:MM)')),
                ('descricao', models.TextField(verbose_name='Descrição do Trabalho Realizado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('advogado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Advogado')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='casos.caso')),
            ],
            options={
                'ordering': ['-data_execucao'],
            },
        ),
    ]
