# Generated by Django 5.2.8 on 2025-11-08 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0003_alter_caso_status'),
        ('clientes', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegraPrazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_minimo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Mínimo Apurado')),
                ('valor_maximo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Máximo Apurado')),
                ('prazo_em_dias', models.PositiveIntegerField(verbose_name='Prazo (em dias)')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Regra de Prazo',
                'verbose_name_plural': 'Regras de Prazos',
                'unique_together': {('cliente', 'produto', 'valor_minimo', 'valor_maximo')},
            },
        ),
    ]
