# Generated by Django 5.2.7 on 2025-10-10 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0003_timesheet'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acordo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total do Acordo')),
                ('numero_parcelas', models.PositiveIntegerField(default=1, verbose_name='Número de Parcelas')),
                ('data_primeira_parcela', models.DateField(verbose_name='Data da 1ª Parcela')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('advogado_acordo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Advogado do Acordo')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acordos', to='casos.caso')),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.PositiveIntegerField(verbose_name='Nº da Parcela')),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Parcela')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('status', models.CharField(choices=[('EMITIDA', 'Emitida'), ('QUITADA', 'Quitada')], default='EMITIDA', max_length=10, verbose_name='Status do Pagamento')),
                ('acordo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='casos.acordo')),
            ],
            options={
                'ordering': ['data_vencimento'],
                'unique_together': {('acordo', 'numero_parcela')},
            },
        ),
    ]
