# Generated by Django 5.2.7 on 2025-10-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0004_acordo_parcela'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcela',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Pagamento'),
        ),
    ]
