# Generated by Django 5.2.8 on 2025-11-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0004_regraprazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='valor_apurado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Valor Apurado'),
        ),
    ]
