# Generated by Django 5.2.7 on 2025-10-10 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0005_parcela_data_pagamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_despesa', models.DateField(verbose_name='Data da Despesa')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Despesa')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição da Despesa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('advogado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Advogado')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='casos.caso')),
            ],
            options={
                'ordering': ['-data_despesa'],
            },
        ),
    ]
