# Generated by Django 5.2.7 on 2025-11-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0005_caso_valor_apurado'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='resumo',
            field=models.TextField(blank=True, help_text='Um resumo executivo do caso, que pode ser gerado pela IA ou inserido manualmente.', null=True, verbose_name='Resumo do Caso'),
        ),
    ]
