# Generated by Django 5.2.7 on 2026-01-18 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0006_caso_resumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tomador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Tomador')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ/CPF')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Tomador',
                'verbose_name_plural': 'Tomadores',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='caso',
            name='tomador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='casos', to='casos.tomador', verbose_name='Tomador'),
        ),
        migrations.CreateModel(
            name='TomadorEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('tomador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='casos.tomador')),
            ],
        ),
        migrations.CreateModel(
            name='TomadorTelefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('tomador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='casos.tomador')),
            ],
        ),
    ]
