# Generated by Django 5.2.7 on 2025-10-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0006_despesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='sharepoint_folder_id',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
    ]
