# Generated by Codex on 2025-02-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0006_caso_resumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='valor_apurado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Valor Apurado'),
        ),
        migrations.AlterField(
            model_name='regraprazo',
            name='valor_minimo',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor Mínimo Apurado'),
        ),
        migrations.AlterField(
            model_name='regraprazo',
            name='valor_maximo',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Valor Máximo Apurado'),
        ),
    ]
