# Generated by Django 5.2.7 on 2025-10-12 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0007_caso_sharepoint_folder_id'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='fase_atual_wf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='workflow.fase', verbose_name='Fase Atual do Workflow'),
        ),
        migrations.AlterField(
            model_name='caso',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Encerrado', 'Encerrado'), ('Em monitoramento', 'Aguardando Documentação')], default='ATIVO', max_length=20),
        ),
    ]
