# Generated by Django 5.2.7 on 2026-01-18 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0007_tomador_caso_tomador_tomadoremail_tomadortelefone'),
        ('clientes', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoTomador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitar_tomador', models.BooleanField(default=True, verbose_name='Habilitar Campo Tomador')),
                ('cliente', models.ForeignKey(blank=True, help_text='Deixe em branco se quiser aplicar a TODOS os clientes deste produto.', null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente', verbose_name='Cliente Específico')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Parametrização de Tomador',
                'verbose_name_plural': 'Parametrizações de Tomador',
                'unique_together': {('produto', 'cliente')},
            },
        ),
    ]
