# Generated by Codex on 2026-01-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0007_alter_valor_apurado_precision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tomador',
            name='cpf_cnpj',
        ),
        migrations.AddField(
            model_name='tomador',
            name='tipo',
            field=models.CharField(choices=[('PF', 'Pessoa Fisica'), ('PJ', 'Pessoa Juridica')], default='PF', max_length=2, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='tomador',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='tomador',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ'),
        ),
    ]
