# Generated by Django 5.2.7 on 2025-10-12 20:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0008_caso_fase_atual_wf_alter_caso_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='status',
            field=models.CharField(choices=[('ATIVO', 'Ativo'), ('ENCERRADO', 'Encerrado'), ('AGUARDANDO_DOC', 'Aguardando Documentação'), ('EM_NEGOCIACAO', 'Em Negociação')], default='ATIVO', max_length=20),
        ),
        migrations.CreateModel(
            name='FluxoInterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('CRIACAO_CASO', 'Criação do Caso'), ('MUDANCA_FASE_WF', 'Mudança de Fase do Workflow'), ('ACAO_WF_CONCLUIDA', 'Ação de Workflow Concluída'), ('ANDAMENTO', 'Andamento Adicionado'), ('TIMESHEET', 'Timesheet Lançado'), ('ACORDO', 'Acordo Criado'), ('DESPESA', 'Despesa Lançada'), ('EMAIL', 'E-mail Enviado'), ('ANEXO', 'Anexo Adicionado')], max_length=20, verbose_name='Tipo do Evento')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_evento', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor da Ação')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fluxo_interno', to='casos.caso')),
            ],
            options={
                'verbose_name': 'Evento do Fluxo Interno',
                'verbose_name_plural': 'Eventos do Fluxo Interno',
                'ordering': ['-data_evento'],
            },
        ),
    ]
