# Generated by Django 5.2.7 on 2026-01-21 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0007_alter_valor_apurado_precision'),
        ('casos', '0008_configuracaotomador'),
    ]

    operations = [
    ]
