# Generated by Django 5.2.7 on 2026-01-21 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0008_tomador_tipo_cpf_cnpj'),
        ('casos', '0009_merge_20260121_0705'),
    ]

    operations = [
    ]
