# Generated by Codex on 2026-01-22
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0010_merge_20260121_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Segurado')),
                ('tipo', models.CharField(choices=[('PF', 'Pessoa Fisica'), ('PJ', 'Pessoa Juridica')], default='PF', max_length=2, verbose_name='Tipo')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Segurado',
                'verbose_name_plural': 'Segurados',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SeguradoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('segurado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='casos.segurado')),
            ],
        ),
        migrations.CreateModel(
            name='SeguradoTelefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('segurado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='casos.segurado')),
            ],
        ),
        migrations.AddField(
            model_name='caso',
            name='segurado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='casos', to='casos.segurado', verbose_name='Segurado'),
        ),
    ]
