# Generated by Codex on 2026-01-22
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0011_segurado'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguradotelefone',
            name='tipo',
            field=models.CharField(choices=[('COMERCIAL', 'Comercial'), ('RESIDENCIAL', 'Residencial'), ('CELULAR', 'Celular')], default='CELULAR', max_length=20, verbose_name='Tipo'),
        ),
    ]
