# Generated by Codex on 2026-01-22
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0012_segurado_telefone_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corretor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do Corretor')),
                ('tipo', models.CharField(choices=[('PF', 'Pessoa Fisica'), ('PJ', 'Pessoa Juridica')], default='PF', max_length=2, verbose_name='Tipo')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Corretor',
                'verbose_name_plural': 'Corretores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='CorretorEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='casos.corretor')),
            ],
        ),
        migrations.CreateModel(
            name='CorretorTelefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('COMERCIAL', 'Comercial'), ('RESIDENCIAL', 'Residencial'), ('CELULAR', 'Celular')], default='CELULAR', max_length=20, verbose_name='Tipo')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('corretor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='casos.corretor')),
            ],
        ),
        migrations.AddField(
            model_name='caso',
            name='corretor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='casos', to='casos.corretor', verbose_name='Corretor'),
        ),
    ]
