# Generated by Codex on 2026-01-23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('casos', '0013_corretor'),
    ]

    operations = [
        migrations.AddField(
            model_name='tomadortelefone',
            name='tipo',
            field=models.CharField(
                choices=[
                    ('COMERCIAL', 'Comercial'),
                    ('RESIDENCIAL', 'Residencial'),
                    ('CELULAR', 'Celular'),
                ],
                default='CELULAR',
                max_length=20,
                verbose_name='Tipo',
            ),
        ),
    ]
