# Generated by Codex on 2026-01-23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('casos', '0015_parcela_comprovante'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='comprovante',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to='comprovantes_despesa/%Y/%m',
                verbose_name='Comprovante',
            ),
        ),
    ]
